---
language: java

# get us on the new container based builds, we're not using any fancyness
sudo: false

branches:
  only:
  - master
  - QATesting

notifications:
  email:
  - anarodriguez0333@gmail.com